def near_same_color(color, target, tolerance=5):
    cr = color[0]
    tr = target[0]
    cg = color[1]
    tg = target[1]
    cb = color[2]
    tb = target[2]
    return abs(cr - tr) <= tolerance \
        and abs(cg - tg) <= tolerance \
        and abs(cb - tb) <= tolerance
